version: "3.9"
services:
    php:
        build:
            context: .
        container_name: ci3-app
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - 7000:7000
        volumes:
            - ./:/ci3
        working_dir: /ci3
        entrypoint: "php -S 0.0.0.0:7000"
    db:
        image: mysql
        container_name: ci3-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ezoom
        ports:
            - "33064:3306"
        volumes:
            - ./system/database/mysql-data:/var/lib/mysql
